#!/bin/bash

# Script de ayuda para navegación de documentación BDNS Web

echo "📚 BDNS Web - Centro de Documentación"
echo "======================================"
echo ""
echo "📖 Documentación Principal:"
echo "  • README.md                    - Visión general del proyecto"
echo "  • CLAUDE.md                    - Instrucciones para Claude AI"
echo ""
echo "📁 Documentación Organizada (./docs/):"
echo ""
echo "🚀 Inicio Rápido:"
echo "  • DEVELOPMENT-GUIDE.md         - Guía completa de desarrollo"
echo "  • DOCKER-SETUP.md              - Configuración Docker"
echo "  • CONFIGURATION-GUIDE.md       - Configuración del sistema"
echo ""
echo "🏗️ Arquitectura:"
echo "  • DATABASE-STRUCTURE.md        - Estructura de BD"
echo "  • API-DOCUMENTATION.md         - Documentación de API"
echo "  • COMPONENTS-GUIDE.md          - Guía de componentes"
echo ""
echo "🔄 Sincronización:"
echo "  • AUTOMATIC-SYNC.md            - Sistema de sincronización"
echo "  • API-CONNECTION.md            - Conexión con BDNS API"
echo ""
echo "🚢 Despliegue:"
echo "  • DEPLOYMENT.md                - Guía de despliegue"
echo "  • PRODUCTION-DEPLOYMENT.md     - Despliegue en producción"
echo ""
echo "📈 Roadmap:"
echo "  • PHASE1-IMPLEMENTATION.md     - Plan Fase 1 (Centro de Docs Web)"
echo "  • IMPROVEMENT-PLAN.md          - Plan de mejoras"
echo "  • BDNS-IMPROVEMENT-SUMMARY.md  - Resumen de mejoras"
echo ""
echo "🔗 Acceso Rápido:"
echo "  • Índice completo: docs/DOCUMENTATION-INDEX.md"
echo "  • Demo en vivo: http://100.29.164.84:3001/"
echo "  • Estado del sistema: http://100.29.164.84:3001/api/sync"
echo ""
echo "Para ver un documento específico:"
echo "  cat docs/[NOMBRE_DOCUMENTO].md"
echo ""
echo "Para buscar en la documentación:"
echo "  grep -r 'término_búsqueda' docs/"